name: phpcs-security-audit

on:
  workflow_dispatch:

jobs:
  phpcs-security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
  
      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"
  
      - name: Install phpcs-security-audit
        run: composer global require --dev pheromone/phpcs-security-audit
  
      - name: Run Security Audit
        run: ~/.composer/vendor/bin/phpcs --standard=Security --report=json --report-file=security_audit_report.json .
  
      - name: Upload Security Audit Report
        uses: actions/upload-artifact@v2
        with:
          name: security-audit-report
          path: security_audit_report.json
